#!/usr/bin/env node

import { Command } from 'commander';

const program = new Command();

program
  .name('<%= projectName %>')
  .description('A new CLI tool generated by Rainar.')
  .version('1.0.0');

program
  .command('hello')
  .description('Say hello')
  .action(() => {
    console.log('Hello, world!');
  });

program.parse(process.argv);
